services:
  - type: web
    name: venda-vapt-vupt
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PIX_CHAVE
        sync: false
      - key: PIX_BENEFICIARIO
        sync: false
      - key: PIX_CIDADE
        sync: false
      - key: UBER_CLIENT_ID
        sync: false
      - key: UBER_CLIENT_SECRET
        sync: false
      - key: UBER_CUSTOMER_ID
        sync: false
      - key: SECRET_KEY
        generateValue: true
